# action.yml
name: 'vsce publish'
description: 'Publish VS Code extension'
branding:
  icon: 'upload-cloud'
  color: 'gray-dark'
inputs:
  build_file:
    description: Build .vsix file
    required: false
    default: false
  vsce_token:
    description: 'vsce token'
    required: true
outputs:
  vsix_path:
    description: Path of the VSIX file
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.build_file }}
    - ${{ inputs.vsce_token }}
